In [2]:
import numpy as np
N = 11
a = np.arange(start = N, stop = -1, step = -1)
print(a)

[11 10  9  8  7  6  5  4  3  2  1  0]


In [3]:
N = 9
np.diag(np.arange(start = N, stop = -1, step = -1))

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
N = 9
np.sum(np.diag(np.diag(np.arange(start = N, stop = -1, step = -1))))

45

In [4]:
import numpy.linalg as la
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
la.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [21]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

print(next_user_stats)
#print()

users_cosines = []
for row in users_stats:
    #print(row)
    #print(next_user_stats)
    #print(cosine(row, next_user_stats))
    users_cosines.append(cosine(row, next_user_stats))

print(users_cosines, max(users_cosines), users_stats[users_cosines.index(max(users_cosines))])


[0 1 2 0 0 0]

[2 1 0 0 0 0]
[0 1 2 0 0 0]
0.19999999999999996
[1 1 2 1 0 0]
[0 1 2 0 0 0]
0.8451542547285165
[2 0 1 0 0 0]
[0 1 2 0 0 0]
0.3999999999999999
[1 1 2 1 0 1]
[0 1 2 0 0 0]
0.7905694150420948
[0 0 1 2 0 0]
[0 1 2 0 0 0]
0.3999999999999999
[0 0 0 0 0 5]
[0 1 2 0 0 0]
0.0
[1 0 0 0 0 0]
[0 1 2 0 0 0]
0.0
[0 1 1 0 0 0]
[0 1 2 0 0 0]
0.9486832980505138
[0 0 0 1 1 3]
[0 1 2 0 0 0]
0.0
[1 0 0 2 1 4]
[0 1 2 0 0 0]
0.0
[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0] 0.9486832980505138 [0 1 1 0 0 0]
